local map = vim.keymap.set

map("n", "<leader>w", ":write<CR>", { desc = "Write to current buffer" })
map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
map("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
map("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
map("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
map("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
map("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
map({ "n", "v" }, "<S-j>", "10j")
map({ "n", "v" }, "<S-k>", "10k")
map({ "n", "v" }, "<leader>y", '"+y')
map({ "n", "v" }, "<leader>si", "<cmd>!isort .<CR>", { desc = "Sort imports" })
map("n", "gH", vim.lsp.buf.hover, { desc = "Hover over symbol" })
